# Generated by Django 4.2.2 on 2023-06-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notekeeper',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
